[build]
  command = "npx prisma generate && npx next build --webpack"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_APP_NAME"

[[plugins]]
  package = "@netlify/plugin-nextjs"